# Generated by Django 6.0 on 2025-12-31 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_project_end_date_remove_project_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='comments',
        ),
    ]
