# Generated by Django 6.0 on 2025-12-31 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
