# Generated by Django 5.2.7 on 2026-01-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_analysis_id_alter_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='raw_material_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
