# Generated by Django 5.2.7 on 2026-01-14 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_raw_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrawmaterial',
            name='raw_material_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_projects', to='api.project'),
        ),
    ]
